remote_theme: hydecorp/hydejack
url: https://heyasher.github.io
title: hey asher
description: Asher Lewis
author: 
  name: Asher Lewis
  social:
    email: asher@heyasher.com

theme: jekyll-theme-minimal